craw_calendar/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]

main/urls.py
from django.urls import path

from . import views

from django.conf import settings
from django.conf.urls.static import static
app_name = 'main'
urlpatterns = [
    path('main', views.index),
    path('', views.index, name='index'),
    path('index', views.index, name='index'),
    path('calendar', views.calendar, name='calendar'),
    path('craw_list_db', views.craw_list_db, name='craw_list_db'),
    path('login', views.login, name='login'),
    path('logout', views.logout, name='logout'),
    path('test', views.test, name='test'),

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_URL)

main/models.py
from django.db import models

# Create your models here.
class Post(models.Model):
    postname = models.CharField(max_length=50)
    contents = models.TextField()

    # 게시글의 제목(postname)이 Post object 대신하기
    def __str__(self):
        return self.postname

class Craw(models.Model):
    snum = models.AutoField(db_column='sNum', primary_key=True)  # Field name made lowercase.
    id = models.CharField(max_length=50)
    lname = models.CharField(db_column='lName', max_length=50)  # Field name made lowercase.
    title = models.TextField()
    degree = models.CharField(max_length=50)
    acheck = models.CharField(db_column='aCheck', max_length=50)  # Field name made lowercase.
    con = models.TextField()
    sdate = models.DateTimeField(db_column='sDate')  # Field name made lowercase.
    edate = models.DateTimeField(db_column='eDate')  # Field name made lowercase.


    class Meta:
        managed = False
        db_table = 'craw'

craw_calendar/forms.py
from django import forms

class NameForm(forms.Form):
    your_id = forms.CharField(label='Your id id', max_length=8)
    your_pw = forms.CharField(label='Your pw pw', max_length=20)

main/forms.py
from django import forms

class LoginForm(forms.Form):
    username = forms.CharField(
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
            }
        )
    )
    password = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                'class': 'form-control',
            }
        )
    )

main/views.py
from django.shortcuts import render
from .models import Craw
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.utils import timezone
from django.urls import reverse
from .forms import LoginForm
from .Craw_inha import Craw_inha
from django.db import connections
import json
from django.http import HttpResponse, JsonResponse
from django.contrib.auth import login as django_login, logout as django_logout, authenticate
from django.contrib.auth.models import User
# index.html 페이지를 부르는 index 함수
def index(request):
    return render(request, 'main/index.html')

def logout(request):
    django_logout(request)
    return render(request, 'main/index.html')

def login(request):
    if request.method == 'POST':
        # Data bounded form인스턴스 생성
        login_form = LoginForm(request.POST)
        # 유효성 검증에 성공할 경우
        if login_form.is_valid():
            # form으로부터 username, password값을 가져옴
            username = login_form.cleaned_data['username']
            password = login_form.cleaned_data['password']

            a = Craw_inha(username, password)
            b = a.crawStart()
            # 인증에 성공했을 경우
            if (b == "로그인 성공"):
                user = authenticate(
                    username=username,
                    password=password
                )
                if user:
                    print("user존재")
                else:
                    #회원가입
                    user = User.objects.create_user(**login_form.cleaned_data)
                # Django의 auth앱에서 제공하는 login함수를 실행해 앞으로의 요청/응답에 세션을 유지한다
                django_login(request, user)

                craw_list = a.craw()
                conn = None
                cur = None
                sql = ""
                try:
                    # db연결
                    conn = connections['default']
                    cur = conn.cursor()

                    # db 테이블 비우기
                    cur.execute("truncate craw")
                    conn.commit()
                except Exception as ex:
                    return render(request, 'main/login.html', {'err': '데이터베이스연동을 실패했습니다.'})
                else:
                    print("db connect")

                # db 데이터 입력
                try:
                    for temp in craw_list:
                        print(temp)
                        sql = "INSERT INTO craw (id, lName, title, degree, aCheck, con, sDate, eDate) VALUES('" + username + "', '" + \
                              temp[0] + "', '" + temp[1] \
                              + "', '" + temp[2] + "', '" + temp[3] + "', '" + temp[4] + "', '" + temp[5] + "', '" + \
                              temp[
                                  6] + "')"

                        cur.execute(sql)
                        conn.commit()
                except Exception as ex:
                    print("data err", ex)
                    conn.close()
                    return render(request, 'main/login.html', {'err': '서버오류'})
                else:
                    print("data good")
                    conn.close()
                    return render(request, 'main/calendar.html')
            else:
                return render(request, 'main/login.html', {'err': '로그인 실패! 아이디와 패스워드를 확인해주세요.'})
        else:
            login_form = LoginForm()
            context = {
                'login_form': login_form,
            }
        return render(request, 'main/login.html', context)
    return render(request, 'main/login.html')


def calendar(request):
    if request.user.is_authenticated:
        return render(request, 'main/calendar.html')
    else:
        return render(request, 'main/login.html')

def craw_list_db(request):
    Craws = Craw.objects.all()
    craw_lists = []
    for craw in Craws:
        if (craw.degree != "[마감]") and (craw.acheck != "제출정보보기"):
            craw_list = {}
            craw_list["title"]=craw.lname
            craw_list["start"]=(craw.sdate).strftime('%Y-%m-%dT%H:%M:%S')
            craw_list["end"]=(craw.edate).strftime('%Y-%m-%dT%H:%M:%S')
            craw_list["extendedProps"]=        {
                'lname' : craw.title,
                'acheck ': craw.acheck ,
                'con': craw.con,

            }
            craw_lists.append(craw_list)
    return JsonResponse(craw_lists, safe=False)

def test(request):
    return render(request, 'main/test.html')

templates/main/calendar.html
{% extends "main/index.html" %}
{% block content %}
<style type="text/css">

    .layer-popup {
      display: none;
      position: fixed;
      top: 0;
      right: 0;
      bottom: 0;
      left: 0;
      background-color: rgba(0, 0, 0, 0.5);
      z-index: 100;
    }

    .layer-popup.show {
      display: block;
    }

    .modal-dialog {
      width: 300px auto;
      margin: 40px auto;
      background-color: #fff;
    }

    .modal-content {
      padding:10px 15px auto;
      line-height: 100px auto;
    }
</style>

<script>
    // 외부영역 클릭 시 팝업 닫기
    $(document).mouseup(function (e){
        $('#layer-popup').hide();
    });

  document.addEventListener('DOMContentLoaded', function() {
    var initialLocaleCode = 'kr';
    var calendarEl = document.getElementById('calendar');
    var calendar = new FullCalendar.Calendar(calendarEl, {
      initialView: 'dayGridMonth',

      headerToolbar: {
        start: "",
        center: "prev title next",
        end: "today",
      },

      locale: initialLocaleCode,


      //높이설정
      contentHeight: 600,
      fixedWeekCount: false,
      showNonCurrentDates: true,
      eventColor : '#eeeeee',



      events: {
        url: "http://localhost:8000/craw_list_db",
        method: "GET",
        failure: function () {
          alert("이벤트를 못가져왔습니다");
        },
      }
      , eventClick: function(info) {
        var eventObj = info.event;
        $("#title").text(eventObj.title);
        $("#lname").text(eventObj.extendedProps.lname);
        $("#con").text(eventObj.extendedProps.con);
        $('#layer-popup').show();
      }
    });
    calendar.render();
  });

</script>
<div id='calendar'></div>
<div class="container">
  <div class="layer-popup" id="layer-popup">
    <div class="modal-dialog">
      <div class="modal-content">
        <table data-toggle="table" class="table table-bordered">
          <thead>
            <tr>
              <th id="title">강의명</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td id="lname">과제명</td>

            </tr>
            <tr>
              <td id="con">내용</td>
            </tr>
          </tbody>
        </table>

      </div>
    </div>
  </div>
</div>
{% endblock %}

templates/main/form_errors.html
{% if err %}
            <div class="alert alert-danger">
                <strong>{{ err }}</strong>
            </div>
{% endif %}

templates/main/index.html
<!DOCTYPE html>
<html lang="ko">
<head>
    {% load static %}
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}">
    <!-- main CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <!-- fullcalendar CSS -->
    <link rel="stylesheet" href="{% static 'lib/main.css' %}">
    <script src='/static/lib/main.js'></script>
    <script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>
    <!-- Bootstrap JS -->
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <title>inhatc Calendar</title>
</head>
<body>
<!-- ------------------------------- [edit] -------------------------------- -->
<!-- 네비게이션바 -->
{% include "main/navbar.html" %}
<!-- ----------------------------------------------------------------------- -->
<!-- 기본 템플릿 안에 삽입될 내용 Start -->
{% block content %}
{% endblock %}
<!-- 기본 템플릿 안에 삽입될 내용 End -->
</body>
</html>

templates/main/login.html
{% extends "main/index.html" %}
{% block content %}
<div class="container my-3">
    <div class="alert alert-light">
        <strong>캘린더는 로그인후 이용이 가능합니다. 로그인시 데이터 수집을 하여 20~40초 기다리셔야됩니다.</strong>
    </div>
    <form method="post" class="post-form" action="{% url 'main:login' %}">
        {% csrf_token %}
        {% include "main/form_errors.html" %}
        <div class="form-group">
            <label for="username">사용자ID</label>
            <input type="text" class="form-control" name="username" id="username"
                   value="{{ form.username.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="password">비밀번호</label>
            <input type="password" class="form-control" name="password" id="password"
                   value="{{ form.password.value|default_if_none:'' }}">
        </div>
        <button type="submit" class="btn btn-light ">로그인</button>
    </form>
</div>
{% endblock %}

templates/main/navbar.html
<!-- 네비게이션바 -->
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
    <a class="navbar-brand" href="{% url 'main:index' %}">inhatc Calendar</a>
    <button class="navbar-toggler ml-auto" type="button" data-toggle="collapse" data-target="#navbarNav"
        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse flex-grow-0" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item ">
                {% if user.is_authenticated %}
                <a class="nav-link" href="{% url 'main:logout' %}">{{ user.username }} (로그아웃)</a>
                {% else %}
                <!-- ----------------------------------------------------------------------- -->
                <a class="nav-link" href="{% url 'main:login' %}">로그인</a>
                <!-- ------------------------------- [edit] -------------------------------- -->
                {% endif %}
            </li>
            <li class="nav-item ">
                <a class="nav-link" href="{% url 'main:calendar' %}">캘린더</a>
            </li>
        </ul>
    </div>
</nav>
<!-- ----------------------------------------------------------------------- -->